language: node_js
sudo: required
node_js:
    - 10
before_install:
install:
script:
  node ./createfile.js $TRAVIS_PULL_REQUEST
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist/$TRAVIS_PULL_REQUEST
    keep-history: true
    on:
        condition: $TRAVIS_PULL_REQUEST > 0
  # - provider: script
  #   script: node ./build.js $NPM_TOKEN
  #   skip-cleanup: true
  #   on:
  #     branch: master
