language: node_js
sudo: required
addons:
    chrome: stable
node_js:
    - 10
before_install:
    - yarn
install:
script:
cache:
    yarn: true
deploy:
  - provider: script
    script: node ./test.js
    on:
      branch: master
  - provider: script
    script: node ./build.js
    on:
      branch: master
