language: node_js
sudo: required
node_js:
    - 10
before_install:
install:
script:
deploy:
  - provider: script
    script: node ./test.js
    skip-cleanup: true
    on:
      branch: master
  - provider: script
    script: node ./build.js $NPM_TOKEN
    skip-cleanup: true
    on:
      branch: master
